# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/alex/vivado/ip_repo/TX_Baseband_0.1/ofdm_baseband/ofdm_baseband.cache/wt [current_project]
set_property parent.project_path /home/alex/vivado/ip_repo/TX_Baseband_0.1/ofdm_baseband/ofdm_baseband.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
set_property ip_repo_paths /home/alex/vivado/ip_repo [current_project]
set_property ip_output_repo /home/alex/vivado/ip_repo/TX_Baseband_0.1/ofdm_baseband/ofdm_baseband.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/alex/vivado/ip_repo/TX_Baseband_0.1/ofdm_baseband/ofdm_baseband.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files /home/alex/vivado/ip_repo/TX_Baseband_0.1/ofdm_baseband/ofdm_baseband.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/alex/vivado/ip_repo/TX_Baseband_0.1/ofdm_baseband/ofdm_baseband.srcs/sources_1/bd/design_1/ip/design_1_xfft_0_0/design_1_xfft_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/alex/vivado/ip_repo/TX_Baseband_0.1/ofdm_baseband/ofdm_baseband.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/alex/vivado/ip_repo/TX_Baseband_0.1/ofdm_baseband/ofdm_baseband.srcs/sources_1/bd/design_1/ip/edit_Cyclic_Prefix_v0_1.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all /home/alex/vivado/ip_repo/TX_Baseband_0.1/ofdm_baseband/ofdm_baseband.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/alex/vivado/ip_repo/TX_Baseband_0.1/ofdm_baseband/ofdm_baseband.srcs/sources_1/bd/design_1/design_1.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
