# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/alex/Documents/Vivado/ip_repo/GitHub/ip_repo/edit_Cyclic_Prefix_v0_1.cache/wt [current_project]
set_property parent.project_path /home/alex/Documents/Vivado/ip_repo/GitHub/ip_repo/edit_Cyclic_Prefix_v0_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
set_property ip_repo_paths {
  /home/alex/Documents/Vivado/ip_repo/GitHub/ip_repo/Cyclic_Prefix_0.1
  /home/alex/Documents/Vivado/ip_repo/GitHub/ip_cores/QAM_Modulator_0.1
  /home/alex/GitHub/parametric_qam/ip_repo/qam_mod_1.0
} [current_project]
set_property ip_output_repo /home/alex/Documents/Vivado/ip_repo/GitHub/ip_repo/edit_Cyclic_Prefix_v0_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/alex/Documents/Vivado/ip_repo/GitHub/ip_repo/Cyclic_Prefix_0.1/src/blk_mem_gen_0/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files /home/alex/Documents/Vivado/ip_repo/GitHub/ip_repo/Cyclic_Prefix_0.1/src/blk_mem_gen_0/blk_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  /home/alex/Documents/Vivado/ip_repo/GitHub/ip_repo/Cyclic_Prefix_0.1/hdl/CP_Top.v
  /home/alex/Documents/Vivado/ip_repo/GitHub/ip_repo/Cyclic_Prefix_0.1/hdl/Cyclic_Prefix_v0_1_S00_AXI.v
  /home/alex/Documents/Vivado/ip_repo/GitHub/ip_repo/Cyclic_Prefix_0.1/hdl/Cyclic_Prefix_v0_1_S00_AXIS.v
  /home/alex/Documents/Vivado/ip_repo/GitHub/ip_repo/Cyclic_Prefix_0.1/hdl/Cyclic_Prefix_v0_1_M00_AXIS.v
  /home/alex/Documents/Vivado/ip_repo/GitHub/ip_repo/Cyclic_Prefix_0.1/hdl/Cyclic_Prefix_v0_1.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Cyclic_Prefix_v0_1 -part xc7z020clg484-1


write_checkpoint -force -noxdef Cyclic_Prefix_v0_1.dcp

catch { report_utilization -file Cyclic_Prefix_v0_1_utilization_synth.rpt -pb Cyclic_Prefix_v0_1_utilization_synth.pb }
